### ISSUE TITLE
Configure to deployed Netifly

### ISSUE THREAD

**Issue by admin-estiem-lg-seville** [ESTIEM-LG-Seville/ELGS-vue#3]
Prepare the directory to be able to deploy the site in Netifly
### ToDo List

- [ ] Create Dist folder and configure it
- [ ] Create Development and staging mode
- [ ] Create Production Mode

### Useful Links
[Dist Folder](https://www.youtube.com/watch?v=W2lGxvNs2KM)
